language: go

go:
  - 1.10.x

install:
  - wget https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -O /tmp/dep
  - chmod +x /tmp/dep
  - /tmp/dep ensure

script:
  - sh test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)